{
 "title": "Tempo Operational",
 "tags": [ "tempo" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "logsds", "query": "loki" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tempo_build_info, k8s_cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tempo_build_info, namespace)"
    }
   },
   {
    "name": "component",
    "query": "compactor,distributor,ingester,metrics-generator,query-frontend,querier,cortex-gw"
   },
   { "name": "cluster_key", "query": "k8s_cluster" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "gcs",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "go heap",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\", container!=\"POD\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "working set",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{$cluster_key=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\", container!=\"POD\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "tx/rx",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
       "legendFormat": "rx-{{pod}}"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
       "legendFormat": "tx-{{pod}}"
      }
     ]
    },
    {
     "title": "data volume free",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{$cluster_key=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$component.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "bad words",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promtail_custom_bad_words_total{$cluster_key=\"$cluster\", exported_namespace=\"$namespace\", app=~\"$component.*\"}[$__rate_interval])",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "%age total work queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "tempodb_work_queue_length{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"} / tempodb_work_queue_max{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "maintenance errors",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tempodb_compaction_errors_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (job)",
       "legendFormat": "compaction_err"
      },
      {
       "expr": "sum(increase(tempodb_retention_errors_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (job)",
       "legendFormat": "retention_err"
      },
      {
       "expr": "sum(increase(tempodb_blocklist_poll_errors_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (job)",
       "legendFormat": "blocklist_err"
      }
     ]
    },
    {
     "title": "Blocklist Poll Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Blocklist Length",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(tempodb_blocklist_length{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}) by (tenant)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "retention duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-compactor\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-compactor\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-compactor\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "retention",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tempodb_retention_deleted_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval]))",
       "legendFormat": "deleted"
      },
      {
       "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval]))",
       "legendFormat": "marked_for_deletion"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Queries/Sec (cortex-gw)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_traces_traceid\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Gateway)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (cortex-gw)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_search.*\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Gateway)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", route=~\".*api_traces_traceid\", job=\"$namespace-query-frontend\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", route=~\".*api_search.*\", job=\"$namespace-query-frontend\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Query Frontend)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-query-frontend\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_traces_traceid\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_search.*\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Querier)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-querier\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Queries/Sec (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=\"/tempopb.Querier/FindTraceByID\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Search Queries/Sec (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"/tempopb.Querier/Search.*\", $cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Search Query Latency (Ingester)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9",
     "stepMode": "min"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans Received",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tempo_distributor_spans_received_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Traces Created",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(tempo_ingester_traces_created_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Blocks Flushed (1h)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tempo_ingester_blocks_flushed_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\"}[1h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Flushes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(tempo_ingester_failed_flushes_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[5m]) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Blocks Cleared (1h)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tempo_ingester_blocks_cleared_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[1h]))"
      }
     ]
    },
    {
     "title": "Flush Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Pushes/sec (gateway)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "OTEL Distributor Spans/second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 7, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempo_receiver_accepted_spans{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "accepted"
      },
      {
       "expr": "sum(rate(tempo_receiver_refused_spans{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "refused"
      }
     ]
    },
    {
     "title": "Push Latency (Gateway)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-cortex-gw\", route=\"opentelemetry_proto_collector_trace_v1_traceservice_export\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Push Latency (Ingester)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 13, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_memcache_request_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (status_code, method)",
       "legendFormat": "{{status_code}}-{{method}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_memcache_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".99-{{method}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_memcache_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".9-{{method}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_memcache_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".5-{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_backend_request_duration_seconds_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_backend_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_backend_request_duration_seconds_bucket{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ring/Memberlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gossip Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gauge_memberlist_health_score{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Health",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tempo_memberlist_client_cluster_node_health_score{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Member Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(tempo_memberlist_client_cluster_members_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(tempo_memberlist_client_cluster_members_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "KV Store Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min(tempo_memberlist_client_kv_store_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"})",
       "legendFormat": "min"
      },
      {
       "expr": "max(tempo_memberlist_client_kv_store_count{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-$component\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Vulture",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vulture Query Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_vulture_trace_error_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(tempo_vulture_trace_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "Average Vulture Query Errors",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(tempo_vulture_trace_error_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(tempo_vulture_trace_total{$cluster_key=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{secondsago}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects Combined / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_objects_combined_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace-compactor\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Objects Written / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_objects_written_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-compactor\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Bytes Written / s",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_bytes_written_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-compactor\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Blocks Compacted",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tempodb_compaction_blocks_total{$cluster_key=\"$cluster\", namespace=\"$namespace\", job=\"$namespace-compactor\"}[5m])) by (level)"
      }
     ]
    }
   ]
  }
 ]
}